### ISSUE TITLE
Missing the code for section 12 'Python and databases'

### ISSUE THREAD

**Issue by iwillneverstop** [PacktPublishing/Python-for-Everyday-Life#11]
I see that there is no code for section 12 'Python and databases'. Could you add?

**Comment by csparpa** [comment]
Hello @iwillneverstop I am the original author of this codes. I think it's Packt Publishing's duty (@jainyash75 ?) to provide the missing folder..

Did you try to contact them via customer service?

**Comment by iwillneverstop** [comment]
Thank you for your reply. I also downloaded the source code directly from https://www.packtpub.com/application-development/python-everyday-life-video. That version is even worse than this version (more sections are missing). 

I haven't contacted them.
